language: java
matrix:
  include:
    - jdk: oraclejdk8
      dist: trusty
    - jdk: oraclejdk9
      dist: trusty
    - jdk: openjdk8
script: mvn test -Djunit.jupiter.execution.parallel.enabled=false
